apiVersion: v1
kind: ConfigMap
metadata:
  name: planetary-config
data:

  # Log Analyser config
  request_timeout: "10"
  repo_scan_frequency: "3600"
  run_scan_frequency: "3600"
  max_threads: "8"

  github_base_url: "{'siemens': 'https://github.siemens.cloud'}"
  azure_base_urls: "{'sol': 'https://sol.tfs.siemens.net', 'jupiter': 'https://jupiter.tfs.siemens.net/tfs'}"

  # API config
  api_host: "0.0.0.0"
  api_port: "8000"

  # Frequency to write energy values back to the database
  service_interval: "3600"

  # Prom config (credentials are in the secret)
  prometheus_host: "https://prometheus-heartbeat.dema-platform.siemens.cloud"
  prometheus_port: "9090"

  # Postgres config (credentials are in the secret)
  postgres_host: "postgres-postgresql"
  postgres_port: "5432"
  postgres_database: "postgres"

  # LDAP config (credentials are in the secret)
  ldap_server: "ldap://ad001.siemens.net"
  ldap_query: "OU=Servers,OU=_Central,OU=005,OU=RA011,DC=ad001,DC=siemens,DC=net"
  ldap_scan_frequency: "3600"
