{
 "title": "Collection",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "query": "select distinct platform_tag from repositories;"
   },
   {
    "name": "collection",
    "label": "collection",
    "query": "select distinct r.collection from repositories r where r.platform_tag = '$platform' order by r.collection;"
   },
   {
    "name": "repositoryID",
    "query": "select id from repositories where collection = '$collection' and project = '$project' and name = '$repository';\n"
   },
   { "name": "PUE", "query": "1.5" },
   { "name": "carbonIntensity", "query": "349" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQefsy6ZB4bN6KiiTKPfp2gfGV3bE9wPQApEQyvIK2h7LbGbcJfKxQkKgKXW5IGwhbYRU0&usqp=CAU\" width=200px/></p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 1 },
   "options": {
    "content": "- Collection: ${collection}\r\n"
   }
  },
  {
   "title": "CO2 kg/TimeRange",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ((sum(job.energy) / 360000) * $PUE * $carbonIntensity) / 1000 as carbon\r\nfrom jobs job \r\njoin runs run on job.run_id = run.id\r\njoin repositories r on run.repository_id = r.id\r\nwhere r.collection = '$collection'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo();\r\n"
    }
   ]
  },
  {
   "title": "Runs Time Range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 1, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from runs run\r\njoin repositories r on r.id = run.repository_id\r\nwhere r.collection = '$collection' and\r\nrun.started_at BETWEEN $__timeFrom() AND $__timeTo();"
    }
   ]
  },
  {
   "title": "Total runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from runs run\r\njoin repositories r on r.id = run.repository_id\r\nwhere r.collection = '$collection';\r\n\r\n"
    }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Energy per day [J]",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', job.start_time) as day, sum(job.energy) as summed_energy\r\nfrom jobs job \r\njoin runs run on job.run_id = run.id\r\njoin repositories r on run.repository_id = r.id\r\nwhere r.collection = '$collection'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\ngroup by day\r\norder by day desc;"
    }
   ]
  },
  {
   "title": "CO2 per day [g]",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 11 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', job.start_time) as day, ((sum(job.energy) / 3600000) * $PUE * $carbonIntensity) as carbon_dioxide\r\nfrom jobs job \r\njoin runs run on job.run_id = run.id\r\njoin repositories r on run.repository_id = r.id\r\nwhere r.collection = '$collection'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\ngroup by day\r\norder by day desc;"
    }
   ]
  },
  {
   "title": "Run times per day [s]",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', job.start_time) as day, (sum(extract(epoch from job.end_time - job.start_time))) as total_runtime from jobs job\r\njoin runs run on job.run_id = run.id\r\njoin repositories r on run.repository_id = r.id\r\nwhere r.collection = '$collection'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\ngroup by day order by day desc;\r\n"
    }
   ]
  },
  {
   "title": "Runs per day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 18 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', started_at) as day, count(*) as number_runs from runs run\r\njoin jobs job on job.run_id = run.id\r\njoin repositories r on run.repository_id = r.id\r\nwhere r.collection = '$collection'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\ngroup by day order by day desc;"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Longest running jobs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "select r.project, r.name as repo_name, job.name as job_name, job.runner, job.end_time - job.start_time as run_time\r\nfrom jobs job \r\njoin runs run on job.run_id = run.id\r\njoin repositories r on run.repository_id = r.id\r\nwhere r.collection = '$collection'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\nORDER BY run_time desc LIMIT 10;"
    }
   ]
  },
  {
   "title": "Longest running steps",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "select r.project, r.name as repo_name, step.name as step_name, job.runner, step.end_time - step.start_time as run_time\r\nfrom jobs job\r\n         join runs run on job.run_id = run.id\r\n         join steps step on job.id = step.job_id\r\n         join repositories r on run.repository_id = r.id\r\nwhere r.collection = '$collection' and run.started_at BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY run_time desc LIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Workflow ID Runs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "select w.id, count(r.id) as run_counter\r\nfrom workflows w\r\njoin runs r on w.id = r.workflow_id\r\njoin repositories repos on w.repository_id = repos.id\r\nwhere repos.collection = '${collection}'\r\ngroup by w.id\r\norder by run_counter desc\r\nlimit 10;"
    }
   ]
  },
  {
   "title": "Run IDs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "select r.name, r.id, r.finished_at - r.started_at as run_time  from runs r\r\njoin repositories repo on r.repository_id = repo.id\r\nwhere repo.collection = '$collection'\r\n  and r.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\norder by run_time desc;"
    }
   ]
  }
 ]
}