{
 "title": "Log analyser",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Repositories",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from repositories;\r\n"
    }
   ]
  },
  {
   "title": "Number of Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*) from runs;\r\n" }
   ]
  },
  {
   "title": "Number of Runners",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from runners WHERE name != 'None';"
    }
   ]
  },
  {
   "title": "Number of runs per day",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', started_at) as day, count(*) as number_runs from runs group by day order by day desc;\r\n"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*) from jobs;\r\n" }
   ]
  },
  {
   "title": "Number of Steps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from steps;\r\n"
    }
   ]
  },
  {
   "title": "Runs per repo",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select concat(repo.collection, '-', repo.project, '-', repo.name), count(*) as number_runs, sum(run.finished_at - run.started_at) as run_time from runs run\r\njoin repositories repo on run.repository_id = repo.id group by repo.name, run.repository_id, repo.collection, repo.project\r\norder by number_runs desc\r\nlimit 10;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Run time per repo [hours]",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 11, "x": 10, "y": 12 },
   "targets": [
    {
     "rawSql": "select concat(repo.collection, '-', repo.project, '-', repo.name), EXTRACT(EPOCH FROM sum(run.finished_at - run.started_at))/3600 as run_time from runs run\r\njoin repositories repo on run.repository_id = repo.id group by repo.name, run.repository_id, repo.collection, repo.project\r\norder by run_time desc\r\nlimit 10;\r\n"
    }
   ]
  },
  {
   "title": "Number Repos per Project",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "select concat(collection, ': ', project) as collection_name, count(*) as number_repositories from repositories group by collection, project order by number_repositories desc limit 10;\r\n"
    }
   ]
  }
 ]
}