{
 "title": "Repository",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "collection",
    "label": "collection",
    "query": "select distinct collection from repositories;\n"
   },
   {
    "name": "project",
    "query": "select repo.project from repositories repo where collection = '$collection';"
   },
   {
    "name": "repository",
    "query": "select repo.name from repositories repo where collection = '$collection' and project = '$project';"
   },
   {
    "name": "repositoryID",
    "query": "select id from repositories where collection = '$collection' and project = '$project' and name = '$repository';\n"
   },
   { "name": "PUE", "query": "1.5" },
   { "name": "carbonIntensity", "query": "349" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQefsy6ZB4bN6KiiTKPfp2gfGV3bE9wPQApEQyvIK2h7LbGbcJfKxQkKgKXW5IGwhbYRU0&usqp=CAU\" width=200px/></p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 1 },
   "options": {
    "content": "- Collection: ${collection}\r\n- Project: ${project}\r\n- Repository ${repository}\r\n- Repository-ID ${repositoryID}"
   }
  },
  {
   "title": "CO2 g/TimeRange",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ((sum(job.energy) / 3600000) * $PUE * $carbonIntensity) as carbon\r\nfrom jobs job join runs run on job.run_id = run.id\r\nwhere run.repository_id = '$repositoryID'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo();"
    }
   ]
  },
  {
   "title": "Runs Time Range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 1, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from runs run where repository_id = '$repositoryID' \r\nand run.started_at BETWEEN $__timeFrom() AND $__timeTo();\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from runs where repository_id = '$repositoryID';\r\n"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy per day",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "select date_trunc('day', job.start_time) as day, sum(job.energy)\r\nfrom jobs job join runs run on job.run_id = run.id\r\nwhere run.repository_id = '$repositoryID'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\ngroup by day\r\norder by day desc;"
      }
     ]
    },
    {
     "title": "CO2 per day [g]",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 9, "x": 10, "y": 11 },
     "targets": [
      {
       "rawSql": "select date_trunc('day', job.start_time) as day, ((sum(job.energy) / 3600000) * $PUE * $carbonIntensity) as carbon\r\nfrom jobs job join runs run on job.run_id = run.id\r\nwhere run.repository_id = '$repositoryID'\r\n  and run.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\ngroup by day\r\norder by day desc;"
      }
     ]
    },
    {
     "title": "Run times [s]",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "select date_trunc('day', job.start_time) as day, (sum(extract(epoch from job.end_time - job.start_time))) as total_runtime from jobs job\r\njoin runs run on job.run_id = run.id \r\nwhere run.repository_id = '$repositoryID' and run.started_at BETWEEN $__timeFrom() AND $__timeTo()\r\ngroup by day order by day desc;\r\n"
      }
     ]
    },
    {
     "title": "Runs per day",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 9, "x": 10, "y": 18 },
     "targets": [
      {
       "rawSql": "select date_trunc('day', started_at) as day, count(*) as number_runs from runs run\r\nwhere repository_id = '$repositoryID' and run.started_at BETWEEN $__timeFrom() AND $__timeTo()\r\ngroup by day order by day desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longest running jobs",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "select job.name, job.runner, job.end_time - job.start_time as run_time from jobs job\r\njoin runs run on job.run_id = run.id\r\nwhere run.repository_id = '$repositoryID' and run.started_at BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY run_time desc LIMIT 10;\r\n"
      }
     ]
    },
    {
     "title": "Longest running steps",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "select step.name, job.runner, step.end_time - step.start_time as run_time\r\nfrom jobs job\r\n         join runs run on job.run_id = run.id\r\n         join steps step on job.id = step.job_id\r\nwhere run.repository_id = '$repositoryID' and run.started_at BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY run_time desc LIMIT 10;\r\n"
      }
     ]
    },
    {
     "title": "Workflow ID Runs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "select w.id, count(r.id) as run_counter\r\nfrom workflows w\r\njoin runs r on w.id = r.workflow_id\r\nwhere w.repository_id = '${repositoryID}'\r\ngroup by w.id\r\norder by run_counter desc\r\nlimit 10;"
      }
     ]
    },
    {
     "title": "Run IDs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "rawSql": "select r.name, r.id, r.finished_at - r.started_at as run_time  from runs r\r\nwhere r.repository_id = '$repositoryID'\r\n  and r.started_at BETWEEN $__timeFrom()\r\n  AND $__timeTo()\r\norder by run_time desc;"
      }
     ]
    }
   ]
  }
 ]
}