{
 "title": "Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "select service_name from services;"
   },
   {
    "name": "subservices",
    "query": "select subservice_name from subservices where service_name= '$service';"
   },
   {
    "name": "hosts_string",
    "query": "SELECT string_agg(server_name_transformed, '|')\nFROM (\n  SELECT LOWER(server_name) || '.ad001.siemens.net' AS server_name_transformed\n  FROM servers\n  WHERE service_name = '$service'  \n  UNION ALL\n  \n  SELECT UPPER(server_name) || '.ad001.siemens.net' AS server_name_transformed\n  FROM servers\n  WHERE service_name = '$service'\n) AS combined_results;"
   },
   {
    "name": "total",
    "query": "SELECT greatest(count(*),1) FROM servers\nWHERE service_name = '$service';"
   },
   { "name": "CO2_factor", "query": "0.350" },
   { "name": "PUE", "query": "1.5" },
   {
    "name": "servers",
    "query": {
     "query": "query_result(planetary_VSphere_vmware_power_power_average{type=\"vm\", vm=~\"$hosts_string\"})"
    }
   },
   {
    "name": "servers_string",
    "query": "SELECT string_agg(val, '|') AS aggregated_string\nFROM unnest(string_to_array('${servers:csv}', ',')) AS t(val);\n"
   }
  ]
 },
 "panels": [
  { "title": "Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service VMs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nFROM servers\r\nWHERE service_name = '$service'\r\n/* AND ($subservices = 'all' OR  subservice_name IN ($subservices)); */"
    }
   ]
  },
  {
   "title": "VM Coverage [%]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum(\r\n    planetary_VSphere_vmware_power_power_average{type=\"vm\", vm=~\"$hosts_string\"}\r\n  ) by (vm)\r\n) / $total * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Power Consumption [W]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"vm\", vm=~\"$hosts_string\"}) / 1000",
     "legendFormat": "Summed Energy"
    }
   ]
  },
  {
   "title": "CO2 kg/h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"vm\", vm=~\"$hosts_string\"}) / 1000000 * ${PUE} * ${CO2_factor}",
     "legendFormat": "Summed Energy"
    }
   ]
  },
  {
   "title": "Power Consumption [W]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 1, "y": 7 },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"vm\", vm=~\"$hosts_string\"}) / 1000",
     "legendFormat": "Summed Energy"
    }
   ]
  },
  {
   "title": "Power Consumption [W]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_power_power_average{type=\"vm\", vm=~\"$hosts_string\"} / 1000",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  { "title": "Physical Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Number Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 1, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(planetary_VSphere_vmware_power_power_average{type=\"host\", host=~\"$servers_string\"})",
     "legendFormat": "Summed Energy"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 19 },
   "options": {
    "content": "### All servers where at least one service VM is running on"
   }
  },
  {
   "title": "Current Power Consumption [W]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"host\", host=~\"$servers_string\"})",
     "legendFormat": "Summed Energy"
    }
   ]
  },
  {
   "title": "Power Consumption [W]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 1, "y": 25 },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"host\", host=~\"$servers_string\"})",
     "legendFormat": "Summed Energy"
    }
   ]
  },
  {
   "title": "CO2 kg/h",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"host\", host=~\"$servers_string\"}) / 1000 * ${PUE} * ${CO2_factor}",
     "legendFormat": "Summed Energy"
    }
   ]
  }
 ]
}