{
 "title": "Vsphere",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "planetary_VSphere_vmware_power_power_average{type=\"host\"}"
    }
   },
   { "name": "cpuMhzFactor", "query": "0.0024" },
   { "name": "hostPowerOffset", "query": "0" }
  ]
 },
 "panels": [
  { "title": "Host Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vsphere Host vs Dell OME Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_power_power_average{host=\"${instance}\", type=\"host\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "planetary_DellOpenManage_dell_openmanage_power{host=\"${instance}\"} offset 60m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere Host vs VM Power Offset ${hostPowerOffset}",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_power_power_average{host=\"${instance}\", type=\"host\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"}) / 1000 + ${hostPowerOffset}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere VMs Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_power_power_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere Host vs VM CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_cpu_usagemhz_average{host=\"${instance}\", type=\"host\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(planetary_VSphere_vmware_cpu_usagemhz_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere VM CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 25 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_cpu_usagemhz_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere Host vs VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_mem_consumed_average{host=\"${instance}\", type=\"host\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(planetary_VSphere_vmware_mem_consumed_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 37 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_mem_consumed_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere Host vs VM Network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_net_usage_average{host=\"${instance}\", type=\"host\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(planetary_VSphere_vmware_net_usage_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere VM Network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 48 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_net_usage_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power vs CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_power_power_average{host=\"${instance}\", type=\"host\", job=\"local-energy-col-erlc-http\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(planetary_VSphere_vmware_cpu_usagemhz_average{host=\"${instance}\", type=\"vm\", job=\"local-energy-col-erlc-http\"}) * ${cpuMhzFactor} + ${hostPowerOffset}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}