{
 "title": "Vsphere Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CO2_factor", "query": "0.350" },
   { "name": "PUE", "query": "1.5" }
  ]
 },
 "panels": [
  { "title": "Power overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number Hosts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(planetary_VSphere_vmware_power_power_average{type=\"host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "planetary_VSphere_vmware_power_power_average{type=\"host\"}"
    }
   ]
  },
  {
   "title": "Number VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(planetary_VSphere_vmware_power_power_average{type=\"vm\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere Host vs Vsphere VM vs Dell OME",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"vm\"}) / 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(planetary_DellOpenManage_dell_openmanage_power offset 60m) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vsphere Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(planetary_VSphere_vmware_power_power_average{type=\"host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dell Open Manage Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 30 },
   "targets": [
    {
     "expr": "sum(planetary_DellOpenManage_dell_openmanage_power offset 60m)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CO2 kg/h",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 1, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(planetary_DellOpenManage_dell_openmanage_power) / 1000) * ${PUE} * ${CO2_factor}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2 kg/day",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(planetary_DellOpenManage_dell_openmanage_power) / 1000) * ${PUE} * ${CO2_factor} * 24",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Past emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CO2 kg/h",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 1, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(planetary_DellOpenManage_dell_openmanage_power{instance=\" local-energy-col-khe-custom\", job=\"local-energy-col-khe-http\"}[1h]) / 1000 * ${PUE} * ${CO2_factor})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2 kg/day",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(planetary_DellOpenManage_dell_openmanage_power{instance=\" local-energy-col-khe-custom\", job=\"local-energy-col-khe-http\"}[1d]) / 1000 * ${PUE} * ${CO2_factor}) * 24",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}