kind: ServiceAccount
apiVersion: v1
metadata:
  name: "cicd-user"
  labels:
    name: "cicd-user"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "cicd-role"
  labels:
    name: "cicd-role"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - services
      - serviceaccounts
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "cicd-user"
  labels:
    name: "cicd-user"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cicd-role
subjects:
  - kind: ServiceAccount
    name: cicd-user

---
kind: Secret
apiVersion: v1
type: "kubernetes.io/service-account-token"
metadata:
  name: cicd-deploy-token
  annotations:
    kubernetes.io/service-account.name: cicd-user