name: Deploy Postgres to EKS

on:
  push:
    branches: [ 'main' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: [ Linux ]
    container: alpine/k8s:1.24.12
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        env:
          KUBECONFIG_SECRET: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG_SECRET" > kubeconfig.yaml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Create config map with init script
        run: |
          kubectl create configmap postgres-init-scripts --from-file=postgres/init.sql --namespace alm-energymonitor --dry-run=client -o yaml | kubectl apply -f - 

      - name: Add helm repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Deploy postgres helm chart to kubernetes cluster
        run: |
          helm upgrade --install --kubeconfig=kubeconfig.yaml postgres bitnami/postgresql --namespace alm-energymonitor -f postgres/values.yaml
          
        
          
